name: Helm

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm:
    name: Run Helm checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4
      - run: helm lint .
        working-directory: helm
      - run: helm template .
        working-directory: helm
      - run: helm package .
        working-directory: helm
